# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16piQboNVwrFWilQi0jBHA4D4i1_Dk9qn
"""

import numpy as np
import matplotlib.pyplot as plt
import sympy as sp
from scipy.integrate import quad

def F(x):
  if (x>0) and (x< 1):
    return 3*(1-x)**2
  elif (x>=1)or(x<=0):
    return 0
  

def g(x):
  if (x>0) and (x< 1):
    return 3*x*(1-x)**2
  elif (x>=1)or(x<=0):
    return 0 



X = np.linspace(-4,4,1000)

Y = [F(x) for x in X]
plt.xlabel('x')
plt.ylabel('$F(x)$')
plt.plot(X,Y)
plt.grid()



mean = quad(g,0,1)
print('mean=',mean)


def h(x):
  if (x>0) and (x< 1):
    return 3*(x-0.25)**2*(1-x)**2
  elif (x>=1)or(x<=0):
    return 0 

variance= quad(h,0,1)
print('variance=',variance)

mean_=0.25
plt.axvline(mean_, color='violet',label='Mean')
plt.legend()
plt.show()