# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mcPifL2uWjEx9qBlwXO2LKT039JBdSOP
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import bernoulli

#100 samples
simlen=int(1e2)

#Probability of the event
prob = 0.5

#Generating sample data using Bernoulli r.v.
data_bern = bernoulli.rvs(size=simlen,p=prob)
#Let this event be B

#A variable to count elements in set A.
elem_in_A=0

#Calculating the number of favorable outcomes.
for i in range(simlen):
  if data_bern[i]==1:
   elem_in_A+=1
      

prob1=1
sz=elem_in_A
#Generating a set A which is a subset of B
new_subset=bernoulli.rvs(size=sz,p=prob1)
#probability of event A and B
pr_of_AB=(elem_in_A)/(simlen) 

#probability of event A
pr_of_A=(sz)/(simlen)


#calculating p(B/A)
pr_BA=(pr_of_AB)/(pr_of_A)




print("Set B",data_bern)
print("Set A",new_subset)
print("Pr(B/A)=",pr_BA)