# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10Z1CMHF0zboLC91-17dLlMzHF-meQ-gP
"""

import matplotlib.pyplot as plt
import numpy as np
x=np.linspace(0,4,10000)
def f(x):
  return ((x*(-0.10105)+0.5)**2)*((2.718)**(-2))


plt.plot(x, f(x))