# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/127VYNLxvHYaluLEGnPcL51_pNAmMYcUq
"""

import numpy as np
from scipy.stats import bernoulli
import random
import matplotlib.pyplot as plt
sample_size = 100000
X_1, X_2, X_3, X_4, X_5,X_6 = 0, 0, 0, 0, 0, 0
#After caliculating the value of k
k = float(1/21)
prob_X_1 = k
prob_X_2 = 2*k
prob_X_3 = 3*k
prob_X_4 = 4*k
prob_X_5 = 5*k
prob_X_6 = 6*k

sample1 = bernoulli.rvs(size = sample_size, p = prob_X_1)
for i in range(sample_size):
  if sample1[i] == 1:
    X_1 += 1

sample2 = bernoulli.rvs(size = sample_size, p = prob_X_2)
for i in range(sample_size):
  if sample2[i] == 1:
    X_2 += 1

sample3 = bernoulli.rvs(size = sample_size, p = prob_X_3)
for i in range(sample_size):
  if sample3[i] == 1:
    X_3 += 1

sample4 = bernoulli.rvs(size = sample_size, p = prob_X_4)
for i in range(sample_size):
  if sample4[i] == 1:
    X_4 += 1

sample5 = bernoulli.rvs(size = sample_size, p = prob_X_5)
for i in range(sample_size):
  if sample5[i] == 1:
    X_5 += 1

    sample6 = bernoulli.rvs(size = sample_size, p = prob_X_6)
for i in range(sample_size):
  if sample6[i] == 1:
    X_6 += 1

p_X_1 = X_1 /sample_size
p_X_2 = X_2 /sample_size
p_X_3 = X_3 /sample_size
p_X_4 = X_4 /sample_size
p_X_5 = X_5 /sample_size
p_X_6 = X_6 /sample_size


print("Probability of showing up three is = %f"%p_X_3)

cases = ["x = 1", "x = 2", "x = 3","x = 4", "x = 5", " x = 6"]
prob_T = [ k, 2*k, 3*k , 4*k , 5*k , 6*k ]
prob_S = [ prob_X_1 , prob_X_2 ,prob_X_3 ,prob_X_4 ,prob_X_5 ,prob_X_6 ]

x = np.arange(len(cases))
plt.bar(x + 0.00, prob_T, color = 'b', width = 0.25, label = 'labelled')
plt.bar(x + 0.25, prob_S, color = 'g', width = 0.25, label = 'Simulated')
plt.xlabel('cases')
plt.ylabel('Probability')
plt.xticks(x + 0.25/2,[1, 2, 3 , 4 , 5 , 6])
plt.legend()
plt.show()